
name: WeSay Installer

on:
  push:
    branches: [ develop ]

jobs:

  build:
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2019]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe (Windows OS)
      uses: microsoft/setup-msbuild@v2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true # So the PATH can be set by this step
      if: ${{ matrix.os == 'windows-2019' }}

    # Run the unit tests
    - name: Restore
      run: nuget restore src/WeSay.sln

    - name: Build
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true # So gitversion can set environment vars during the build
      run: msbuild src/WeSay.sln /p:Configuration=Release /p:Platform=x86
        
    - name: Build Installer
      run: msbuild build/Installer.targets /p:Configuration=Release /p:Platform=x86 /t:BuildRelease
      
    - name: Publish Installer
      uses: actions/upload-artifact@v4
      with:
        name: WeSayInstallers
        path: BuildDir/WeSay*.exe
